# Hypothesis Testing: Impact of Musical Features on Streams

## Import python libraries and download cleaned dataset

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import matplotlib.pyplot as plt
from scipy import stats

# Đọc luôn file dữ liệu SẠCH từ thư mục processed của bạn nhóm
# Dùng đường dẫn tương đối này thì ai trong nhóm mở máy lên cũng chạy được
df = pd.read_csv("../datasets/processed/cleaned_spotify_2023.csv")

# Xem qua các thông số trung bình, lớn nhất, nhỏ nhất
df[["danceability_%", "energy_%", "streams"]].describe()

       danceability_%    energy_%       streams
count      952.000000  952.000000  9.520000e+02
mean        66.984244   64.274160  5.141374e+08
std         14.631282   16.558517  5.668569e+08
min         23.000000    9.000000  2.762000e+03
25%         57.000000   53.000000  1.416362e+08
50%         69.000000   66.000000  2.905309e+08
75%         78.000000   77.000000  6.738690e+08
max         96.000000   97.000000  3.703895e+09

## 1. Phân tích tương quan (Correlation Analysis)

### a. Kiểm định Pearson Correlation

In [5]:
# Phân tích tương quan (Correlation Analysis)

# Chọn các biến mục tiêu
features = ['danceability_%', 'energy_%']
target = 'log_streams'

print("--- Kết quả phân tích tương quan ---")
# Kiểm định Pearson (tương quan tuyến tính)
pearson_corr = df[[target] + features].corr(method='pearson')
print("\nMa trận tương quan Pearson:")
display(pearson_corr)

--- Kết quả phân tích tương quan ---

Ma trận tương quan Pearson:

                log_streams  danceability_%  energy_%
log_streams        1.000000       -0.068896 -0.026903
danceability_%    -0.068896        1.000000  0.198485
energy_%          -0.026903        0.198485  1.000000

### b. Kiểm định Spearman Rank Correlation

In [6]:
# Kiểm định Spearman (tương quan phi tuyến)
spearman_corr = df[[target] + features].corr(method='spearman')
print("\nMa trận tương quan Spearman:")
display(spearman_corr)

Ma trận tương quan Spearman:

                log_streams  danceability_%  energy_%
log_streams        1.000000       -0.081668 -0.032472
danceability_%    -0.081668        1.000000  0.147977
energy_%          -0.032472        0.147977  1.000000

## 2. Xây dựng mô hình Hồi quy tuyến tính bội (Multiple Linear Regression)

## 3. Xây dựng mô hình Hồi quy tuyến tính bội (Multiple Linear Regression)

### **a. Giả định về phân phối chuẩn của sai số (Normality of Residuals):** 
#### Sử dụng biểu đồ Q-Q Plot và kiểm định Jarque-Bera.

### **b. Giả định về phương sai sai số không đổi (Homoscedasticity):** 
#### Vẽ biểu đồ Residuals vs Fitted plot để quan sát độ phân tán.

### **c. Kiểm tra đa cộng tuyến (Multicollinearity):** 
#### Tính toán chỉ số VIF (Variance Inflation Factor) giữa `danceability_%` và `energy_%`.